# pytest.ini
[pytest]
python_files = *_tests.py test_*.py

markers =
    ui: Для UI тестов
    smoke: Для смоук тестов
    registration: Для тестов регистрации
    slow: Для медленных тестов
    critical: Для критичных тестов
    regression: Для регрессионных тестов
    authorization: Для тестов авторизации
    courses: Для тестов, связанных с курсами