# pytest.ini
[pytest]
python_files = *_tests.py test_*.py

markers =
    ui: Запускает все UI автотесты
    smoke: Запускает skoke автотестов
    registration: Запускает регистрационные автотесты
    slow: Запускает медленные автотесты
    critical: Запускает критичные тесты
    regression: Запускает регрессионные автотесты
    authorization: Запуск тестов авторизации