from enum import Enum

class AllureTags(str, Enum):
    COURSES = 'COURSES'
    DASHBOARDS = 'DASHBOARDS'
    REGRESSIONS = 'REGRESSIONS'
    USER_LOGIN = 'USER_LOGIN'
    NAVIGATION = 'NAVIGATION'
    REGISTRATION = 'REGISTRATION'
    AUTHORIZATION = 'AUTHORIZATION'