name: UI_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: run Playwright tests with pytest and generate Allure result
        run: |
          pytest -m regression --alluredir=./allure-results --numprocesses=4

      - name: Upload Artifacts for Deploy report to GitHub Pages
        uses: actions/upload-artifact@v7
        with:
          name: allure-results
          path: allure-results

  publish-report:
    runs-on: ubuntu-latest
    needs: run-tests
    if: always()

    steps:
      - name: Download Artifacts from jobs "run-tests"
        uses: actions/download-artifact@v5
        with:
          name: allure-result
          path: allure-result

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          fetch-depth: 0
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure-results: allure-results
          allure-history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history